package com.shavatech.management.infraestructure.websocket;

public enum CommandType {
    LIST_PATIENT_HISTORY, CREATE_DIAGNOSIS, UPDATE_DIAGNOSIS,
     LIST_PATIENTS, LIST_TEACHERS, LIST_THERAPISTS, LIST_DOCTORS,
     LIST_SCHEDULES, CREATE_APPOINTMENT, UPDATE_APPOINTMENT, DELETE_APPOINTMENT;
}
